name: Matrix
on: [push]

# Nel contesto di GitHub Actions, una matrice è un meccanismo che ti permette di eseguire lo stesso job più volte in parallelo, variando automaticamente uno o più parametri.
# In pratica, GitHub genera più "istanze" del job, una per ogni combinazione dei valori definiti nella matrix.

# Definendo il parametro node-version con i valori [14, 15, 16], GitHub Actions creerà tre istanze del job node-matrix:
# con matrix.node-version = 14
# con matrix.node-version = 15
# con matrix.node-version = 16

# Con include ed exclude puoi aggiungere o rimuovere combinazioni specifiche.

# exclude
# Serve per escludere alcune combinazioni che la matrice genererebbe di default.

# include
# Serve per aggiungere combinazioni specifiche o aggiungere parametri extra che non verrebbero creati automaticamente dalla matrice.

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
        includes:
          - os: ubuntu-latest
            node-version: 18
          - os: windows-latest
            node-version: 18
        excludes:
          - os: windows-latest
            node-version: 14
          - os: windows-latest
            node-version: 15
          - os: windows-latest
            node-version: 16
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v