# Funzioni di stato in GitHub Actions
# Sono funzioni che GitHub Actions mette a disposizione per l’attributo if:. Servono a controllare la condizione di esecuzione degli step o dei job, in base all’esito di quelli precedenti.

# success()
# Ritorna true se tutti gli step precedenti (nel job) sono andati a buon fine.

# failure()
# Ritorna true se almeno uno degli step precedenti è fallito.

# cancelled()
# Ritorna true se il workflow è stato cancellato manualmente o interrotto.

# always()
# Ritorna sempre true, indipendentemente da successi, fallimenti o cancellazioni.

name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Step 2
        id: step-2
        continue-on-error: true
        run: exit 1
      - name: Runs on step 2 Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has failed'
      - name: Runs on Failure
        if: failure()
        run: echo 'Failure'
      - name: Runs on Success
        if: success()
        run: echo 'Runs on Success'
      - name: Always Runs
        if: always()
        run: echo 'Always Runs'
      - name: Runs When Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'