name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
          - name: Settings an error message
            run: echo "::error::Missing semicolon"